
// EXISTEN 3 POSIBILIDADES DE LLAMAR AL H1 QUE ESTA EN EL DOM
console.log(document.querySelector("h1"));
console.log(document.querySelector(".text-primary"));

// COMO EL METODO QUERYSELECTOR ES UN SELECTOR IGUAL QUE CSS, SE PUEDE LLAMAR AL H1, USANDO ALMOHADILLA, PUNTO O EL NOMBRE DE LA ETIQUETA. 

// EXISTEN 3 CLASES CON EL NOMBRE DE TEXT-DANGER, PERO SIEMPRE VA A SELECCIONAR EL PRIMERO DE TODOS QUE COINCIDA CON EL NOMBRE DE LA CLASE.
console.log(document.querySelector(".text-danger"));

/* PARA SELECCIONAR A TODOS LOS TEXT-DANGER Y SE MUESTREN EN LA CONSOLA, SE
SE PUEDE USAR querySelectorAll */ 
console.log(document.querySelectorAll(".text-danger"));

/* AHORA PARA SELEECIONAR SOLO LO QUE ESTA DENTRO DEL CONTAINER SE DEBE INVOCAR AL CONTAINER 
Y SE MOSTRARA EN CONSOLA */
console.log(document.querySelectorAll(".container .text-danger"));


